;/* Version e2cb5463010d357205cea2144c54cf70 v:4.4.1.154, c:995eeb086d7bbb8daafe17dc413966b004255837, b:4.4.1.154 n:INTERNAL-BUILD */
window['adrum-start-time'] = new Date().getTime();
(function(config){
    config.appKey = 'EUM-AAB-AWG';
    config.adrumExtUrlHttp = 'http://edge.ldscdn.org/cdn2/itt/appd';
    config.adrumExtUrlHttps = 'https://edge.ldscdn.org/cdn2/itt/appd';
    config.beaconUrlHttp = 'http://eum.ldschurch.org';
    config.beaconUrlHttps = 'https://eum.ldschurch.org';
    config.xd = {enable : false};
})(window['adrum-config'] || (window['adrum-config'] = {}));

(function(){new function(){if(!window.ADRUM&&!0!==window["adrum-disable"]){var g=window.ADRUM={},z=window.console,A=z&&"function"==typeof z.log?z:{log:function(){}};window["adrum-start-time"]=window["adrum-start-time"]||(new Date).getTime();(function(a){(function(a){a.Cd=function(){for(var a=[],b=0;b<arguments.length;b++)a[b-0]=arguments[b];for(b=0;b<a.length;b++){var c=a[b];c&&c.setUp()}}})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(b){function f(a){return y.slice.apply(a,y.slice.call(arguments,
1))}function d(a){return"undefined"!==typeof a&&null!==a}function c(a){return"object"==typeof a&&!b.isArray(a)&&null!==a}function e(a){return"function"==typeof a||!1}function m(a){return"string"==typeof a}function h(a,d){for(var x in d){var e=d[x];if(l(d,x)){var m=a[x];c(e)&&c(m)?h(m,e):b.isArray(m)&&b.isArray(e)?a[x]=m.concat(e):a[x]=e}}return a}function l(a,b){return Object.prototype.hasOwnProperty.call(a,b)&&d(a[b])}function k(a){return m(a)?a.replace(/^\s*/,"").replace(/\s*$/,""):a}function q(a,
b){var c=Array.prototype[a];return c?g(c):n(a,b)}function g(a){return function(b){return a.apply(b,f(arguments,1))}}function n(a,b){return function(c,l){if(!d(c))throw new TypeError(a+" called on null or undefined");if(!e(l))throw new TypeError(l+" is not a function");return b.apply(null,arguments)}}function s(a,b,c){var d=Object(a),e=d.length>>>0,l=0;if(3>arguments.length){for(;l<e&&!(l in d);)l++;if(l>=e)throw new TypeError("Reduce of empty array with no initial value");c=d[l++]}for(;l<e;l++)l in
d&&(c=b(c,d[l],l,d));return c}function t(a,c,d){return b.reduce(a,function(a,b,e,l){a[e]=c.call(d,b,e,l);return a},Array(a.length>>>0))}function u(a,c,d){return b.reduce(a,function(a,b,e,l){c.call(d,b,e,l)&&a.push(b);return a},[])}var y={isArray:Array.isArray,toString:Object.prototype.toString,slice:Array.prototype.slice};b.La=f;b.isDefined=d;b.isArray=e(y.isArray)&&e(y.isArray.bind)?y.isArray.bind(Array):function(a){return y.toString.call(a)===y.toString.call([])};b.isObject=c;b.isFunction=e;b.isString=
m;b.isNumber=function(a){return"number"==typeof a};b.isBoolean=function(a){return"boolean"==typeof a};b.Ba=function(a){setTimeout(a,0)};b.addEventListener=function(b,c,d){function e(){try{return d.apply(this,f(arguments))}catch(l){a.exception(l,"M1",c,b,l)}}a.isDebug&&a.log("M0",c,b);b.addEventListener?b.addEventListener(c,e,!1):b.attachEvent&&b.attachEvent("on"+c,e)};b.loadScriptAsync=function(b){var c=document.createElement("script");c.async=!0;c.src=b;var d=document.getElementsByTagName("script")[0];
d?(d.parentNode.insertBefore(c,d),a.log("M2",b)):a.log("M3",b)};b.mergeJSON=h;b.hasOwnPropertyDefined=l;b.$h=function(a){var c=[];d(a)&&(c=b.isArray(a)?a:[a]);return c};b.generateGUID=function(a){return d(a)&&e(a.getRandomValues)&&function(){function b(a){a=a.toString(16);return"0000".substr(a.length)+a}var c=new Uint16Array(8);a.getRandomValues(c);return b(c[0])+b(c[1])+"_"+b(c[2])+"_"+b(c[3])+"_"+b(c[4])+"_"+b(c[5])+b(c[6])+b(c[7])}}(window.crypto||window.msCrypto)||function(){return"xxxxxxxx_xxxx_4xxx_yxxx_xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};b.Md=function(a){return a?(a=a.stack)&&"string"===typeof a?a:null:null};b.trim=k;b.ih=function(a){var b={},c,d;if(!a)return b;var e=a.split("\n");for(d=0;d<e.length;d++){var l=e[d];c=l.indexOf(":");a=k(l.substr(0,c)).toLowerCase();c=k(l.substr(c+1));a&&(b[a]=b[a]?b[a]+(", "+c):c)}return b};b.tryPeriodically=function(a,b,c,d){function e(){if(b())c&&c();else{var h=a(++l);0<h?setTimeout(e,h):d&&d()}}var l=0;e()};b.kc=function(a){return a.charAt(0).toUpperCase()+
a.slice(1)};b.fd=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];return function(){for(var c=[],d=0;d<arguments.length;d++)c[d-0]=arguments[d];return a.apply(this,b.concat(c))}};b.now=function(){return(new Date).getTime()};b.si=s;b.reduce=q("reduce",s);b.ri=t;b.map=q("map",t);b.qi=u;b.filter=q("filter",u);b.Gf=function(a){return b.filter(a,d)};b.yf=function(a){return[].concat.apply([],a)}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){var b=a.conf||(a.conf={});b.userConf=
window["adrum-config"]||{};b.useHTTPSAlways=!0===b.userConf.useHTTPSAlways;b.beaconUrlHttp=a.utils.isDefined(b.userConf.beaconUrlHttp)?b.userConf.beaconUrlHttp:"http://col.eum-appdynamics.com";b.beaconUrlHttps=a.utils.isDefined(b.userConf.beaconUrlHttps)?b.userConf.beaconUrlHttps:"https://col.eum-appdynamics.com";b.corsEndpointPath="/eumcollector/beacons/browser/v1";b.imageEndpointPath="/eumcollector/adrum.gif?";b.appKey=b.userConf.appKey||window["adrum-app-key"]||"APP_KEY_NOT_SET";a=b.useHTTPSAlways||
"https:"===document.location.protocol;var f=b.userConf.adrumExtUrlHttp||"http://cdn.appdynamics.com",d=b.userConf.adrumExtUrlHttps||"https://cdn.appdynamics.com";b.adrumExtUrl=(a?d:f)+"/adrum-ext.e2cb5463010d357205cea2144c54cf70.js";b.adrumXdUrl=d+"/adrum-xd.e2cb5463010d357205cea2144c54cf70.html";b.agentVer="4.4.1.154";b.sendImageBeacon=b.userConf.beacon&&b.userConf.beacon.sendImageBeacon||window["adrum-send-image-beacon"];window["adrum-geo-resolver-url"]?(f=window["adrum-geo-resolver-url"],d=f.indexOf("://"),
-1!=d&&(f=f.substring(d+3)),f=(a?"https://":"http://")+f):(f=b.userConf.geoResolverUrlHttps||"",d=b.userConf.geoResolverUrlHttp||"",f=a?f:d);b.geoResolverUrl=f;b.useStrictDomainCookies=!0===window["adrum-use-strict-domain-cookies"];b.Ge=10})(g||(g={}));(function(a){function b(b,c,d,e){b=a.conf.beaconUrlHttps+"/eumcollector/error.gif?version=1&appKey="+d+"&msg="+encodeURIComponent(b.substring(0,500));e&&(b+="&stack=",b+=encodeURIComponent(e.substring(0,1500-b.length)));return b}function f(c,d){2<=
n||(document.createElement("img").src=b(c,0,a.conf.appKey,d),n++)}function d(a){return 0<=a.location.search.indexOf("ADRUM_debug=true")||0<=a.cookie.search(/(^|;)\s*ADRUM_debug=true/)}function c(b){a.isDebug&&q.push(h(arguments).join(" | "))}function e(a){g.push(h(arguments).join(" | "))}function m(a){var b=h(arguments).join(" | ");c(b);f(b,null)}var h=a.utils.La,l=a.utils.reduce,k=a.utils.isDefined;a.iDR=d;(function(a){a[a.API_ERROR=0]="API_ERROR";a[a.API_ERROR_INVALID_PARAMS=1]="API_ERROR_INVALID_PARAMS";
a[a.API_ERROR_INVALID_CONFIG=2]="API_ERROR_INVALID_CONFIG";a[a.API_WARNING=3]="API_WARNING";a[a.API_WARNING_INEFFECTIVE_CONFIG=4]="API_WARNING_INEFFECTIVE_CONFIG"})(a.ae||(a.ae={}));a.ia=["JS Agent API Error:","JS Agent API Error Invalid Parameters: ","JS Agent API Error Invalid Configs: ","JS Agent API Warning:","JS Agent API Warning Ineffective Config:"];a.U=" a constructor is called as a function. Don't forget keyword new.";a.isDebug=d(document);a.apiMessageConsoleOut=k(a.conf.userConf)&&k(a.conf.userConf.log)&&
!0===a.conf.userConf.log.apiMessageConsoleOut?!0:!1;var q=[],g=[];a.logMessages=q;a.apiMessages=g;a.log=c;a.Ji=e;a.error=m;a.reportAPIMessage=function(b,c,d,l){var h=a.lh.apply(this,arguments);e(h);a.apiMessageConsoleOut&&A.log(h);return h};a.exception=function(){if(!(1>arguments.length)){var b=h(arguments),d=a.utils.Md(b[0]),b=b.slice(1).join(" | ");c(b);f(b,d)}};a.assert=function(a,b){a||m("Assert fail: "+b)};a.dumpLog=a.isDebug?function(){return l(q,function(a,b){return a+b.replace(/\<br\/\>/g,
"\n\t")+"\n"},"")}:function(){};a.lh=function(b,c,d,e){var l="",l="",h=(new window.Error).stack,m,h=a.utils.isString(h)?h.substring(5):h+"";k(m)||(m=a.utils.map(e,function(a){return null===a?"null":void 0==a?"undefined":""===a?"''":a}));switch(b){case 0:case 3:l=a.ia[b];l=k(d)?""+l+c+"\n in "+d+"("+m.join(", ")+")\n"+h:""+l+c+"\n"+h;break;case 1:l=a.ia[b];l=""+l+c+"\nin "+d+"("+m.join(", ")+")\n"+h;break;case 2:case 4:l=a.ia[b];l=""+l+c+", but "+d+"="+m.join(", ")+"\n"+h;break;default:l=a.ia[0],l=
""+l+c+"\nin "+d+"("+m.join(", ")+")\n"+h}return l};a.cIEBU=b;var n=0;c("M4")})(g||(g={}));(function(a){var b=function(){function a(b){this.max=b;this.Oa=0}a.prototype.vg=function(){this.va()||this.Oa++};a.prototype.va=function(){return this.Oa>=this.max};a.prototype.reset=function(){this.Oa=0};return a}(),f=function(){function d(){this.oa=[];this.qb=new b(d.Re);this.eb=new b(d.Ke)}d.prototype.submit=function(b){this.push(b)&&a.initEXTDone&&this.processQ()};d.prototype.processQ=function(){for(var b=
this.Kf(),d=0;d<b.length;d++){var m=b[d];"function"===typeof a.commands[m[0]]?(a.isDebug&&a.log("M5",m[0],m.slice(1).join(", ")),a.commands[m[0]].apply(a,m.slice(1))):a.error("M6",m[0])}};d.prototype.Mg=function(a){return"reportXhr"===a||"reportPageError"===a};d.prototype.push=function(b){var d=b[0],m=this.Mg(d),h=m?this.qb:this.eb;if(h.va())return a.log("M7",m?"spontaneous":"non spontaneous",d),!1;this.oa.push(b);h.vg();return!0};d.prototype.Kf=function(){var a=this.oa;this.reset();return a};d.prototype.size=
function(){return this.oa.length};d.prototype.reset=function(){this.oa=[];this.qb.reset();this.eb.reset()};d.prototype.isSpontaneousQueueDead=function(){return this.qb.va()};d.prototype.isNonSpontaneousQueueDead=function(){return this.eb.va()};d.Re=100;d.Ke=100;return d}();a.he=f})(g||(g={}));(function(a){a.q=new a.he;a.command=function(b){for(var f=1;f<arguments.length;f++);a.isDebug&&a.log("M8",b,Array.prototype.slice.call(arguments).slice(1).join(", "));a.q.submit(Array.prototype.slice.call(arguments))}})(g||
(g={}));(function(a){(function(a){var f=function(){function a(){this.status={}}a.prototype.setUp=function(){};a.prototype.set=function(a,b){this.status[a]=b};return a}();a.Hb=f})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.La;window.ADRUM.aop=b;b.support=function(a){return!a||"apply"in a};b.around=function(d,c,e,m,h){a.assert(b.support(d),"aop.around called on a function which does not support interception");d=d||function(){};return function(){a.isDebug&&a.log("M9",
m,f(arguments).join(", "));var b=f(arguments),k;try{c&&(k=c.apply(this,b))}catch(q){a.exception(q,"M10",m,q)}a.assert(!k||a.utils.isArray(k));var g=void 0;try{g=d.apply(this,k||b)}catch(n){throw h&&h(n),n;}finally{try{e&&e.apply(this,b)}catch(s){a.exception(s,"M11",m,s)}}return g}};b.before=function(a,c,e){return b.around(a,c,null,e)};b.after=function(a,c,e){return b.around(a,null,c,e)}})(a.aop||(a.aop={}))})(g||(g={}));(function(a){a=a.EventType||(a.EventType={});a[a.PageView=0]="PageView";a[a.Ajax=
2]="Ajax";a[a.VPageView=3]="VPageView";a[a.Error=4]="Error";a[a.IFRAME=1]="IFRAME";a[a.ABSTRACT=100]="ABSTRACT";a[a.ADRUM_XHR=101]="ADRUM_XHR";a[a.NG_VIRTUAL_PAGE=102]="NG_VIRTUAL_PAGE"})(g||(g={}));(function(a){a=a.events||(a.events={});a.w={};a.w[100]={guid:"string",url:"string",parentGUID:"string",parentUrl:"string",parentType:"number",timestamp:"number"};a.w[3]={resTiming:"object"};a.w[102]={digestCount:"number"};a.w[2]={method:"string",parentPhase:"string",parentPhaseId:"number",error:"object",
parameter:"object",xhrStatus:"number"};a.w[101]={allResponseHeaders:"string"};a.w[4]={msg:"string",line:"number",stack:"string"}})(g||(g={}));(function(a){var b=function(){function a(){this.D={}}a.prototype.mark=function(a,b){f.mark.apply(this,arguments)};a.prototype.getTiming=function(a){return(a=this.getEntryByName(a))&&a.startTime};a.prototype.measure=function(a,b,d){f.measure.apply(this,arguments)};a.prototype.getEntryByName=function(a){return f.getEntryByName.call(this,a)};a.Na=function(a){return f.Na(a)};
return a}();a.PerformanceTracker=b;var f;(function(b){var c=a.utils.hasOwnPropertyDefined,e=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance,m=a.utils.isObject(e)&&a.utils.isObject(e.timing)&&a.utils.isNumber(e.timing.navigationStart)?e.timing.navigationStart:window["adrum-start-time"],h=a.utils.now;b.mark=function(b,c){this.D[b]={name:b,entryType:"mark",startTime:a.utils.isDefined(c)?c:h(),duration:0}};b.measure=function(b,d,e){c(this.D,d)&&c(this.D,e)?this.D[b]=
{name:b,entryType:"measure",startTime:d?this.D[d].startTime:m,duration:(e?this.D[e].startTime:h())-(d?this.D[d].startTime:m)}:a.error("M12",c(this.D,d)?e:d)};b.getEntryByName=function(a){return this.D[a]||null};b.Na=function(a){return a+m}})(f||(f={}))})(g||(g={}));(function(a){(function(b){function f(b,c){b=b||{};for(var d in b)c[d]=function(){var c=d,m=b[d];return function(b){var d="_"+c,e=this[d];if(a.utils.isDefined(b))if(typeof b===m)this[d]=b;else throw d="wrong type of "+c+" value, "+typeof b+
" passed in but should be a "+m+".",a.reportAPIMessage(1,d,"ADRUM.report",Array.prototype.slice.call(arguments)),TypeError(d);return e}}()}function d(a){var b={},c;for(c in a){var d=a[c];b[d.start]=!0;b[d.end]=!0}return b}var c=function(){function b(c){this.perf=new a.PerformanceTracker;"Object"===this.constructor.name&&a.reportAPIMessage(0,a.U);this.timestamp(a.utils.now());this.guid(a.utils.generateGUID());this.url(document.URL);this.Ea(c)}b.prototype.type=function(){return 100};b.prototype.Ea=
function(b){if(a.utils.isObject(b))for(var c in b){var d=this[c]||this["mark"+a.utils.kc(c)];d&&a.utils.isFunction(d)&&d.call(this,b[c])}};b.fc=function(a,b,c){return{guid:function(){return a},url:function(){return b},type:function(){return c}}};b.prototype.jg=function(){return b.fc(this.parentGUID(),this.parentUrl(),this.parentType())};b.prototype.parent=function(b){var c=this.jg();a.utils.isDefined(b)&&(a.utils.isFunction(b.guid)&&a.utils.isFunction(b.url)&&a.utils.isFunction(b.type)?(this.parentGUID(b.guid()),
this.parentUrl(b.url()),this.parentType(b.type())):a.reportAPIMessage(0,"object is not a valid EventIdentifier","EventTracker.parent",Array.prototype.slice.call(arguments)));return c};return b}();b.EventTracker=c;b.$=f;b.gc=function(b,c){b=b||{};var h=d(b),l;for(l in h)h=a.utils.kc(l),c["mark"+h]=a.utils.fd(function(a,b){this.perf.mark(a,b)},l),c["get"+h]=a.utils.fd(function(a){return this.perf.getTiming(a)},l)};f(b.w[100],c.prototype)})(a.events||(a.events={}))})(g||(g={}));var v=this.hf||function(a,
b){function f(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);f.prototype=b.prototype;a.prototype=new f};(function(a){(function(b){var f=function(b){function c(e){this.constructor!=c?a.reportAPIMessage(0,a.U,"ADRUM.events.Error",[]):b.call(this,e)}v(c,b);c.prototype.type=function(){return 4};return c}(b.EventTracker);b.Error=f;b.$(b.w[4],f.prototype)})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=function(b){function c(){b.apply(this,arguments)}v(c,b);
c.prototype.setUp=function(){var c=this;b.prototype.setUp.call(this);a.listenForErrors=function(){c.Vc()};this.Vc()};c.prototype.qh=function(){c.Ta=0};c.prototype.pd=function(b,d,h,l){c.Ta>=a.conf.Ge?a.log("M13"):(l=a.utils.Md(l),a.command("reportPageError",new a.events.Error(a.utils.mergeJSON({msg:b+"",url:a.utils.isString(d)?d:void 0,line:a.utils.isNumber(h)?h:void 0,stack:l},this.status))),c.Ta++,c.hadErrors=!0)};c.prototype.Vc=function(){var b=this;a.aop.support(window.onerror)?(window.onerror=
a.aop.around(window.onerror,function(a,d,l,f,g){c.ab||(b.pd(a,d,l,g),c.ab=!0)},function(){c.ab=!1},"onerror"),a.log("M14")):a.log("M15")};c.ab=!1;c.Ta=0;c.hadErrors=!1;return c}(b.Hb);b.ErrorMonitor=f;b.ra=new b.ErrorMonitor})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){var b=function(){function b(){this.Ga=[];this.Aa(b.Ja,0)}b.prototype.Zg=function(a){this.Aa(b.$b,a)};b.prototype.ah=function(a){this.Aa(b.hc,a)};b.prototype.$g=function(a){this.Aa(b.bc,a)};b.prototype.Aa=function(a,b){this.Ga.push({Yg:(new Date).getTime(),
Xg:b,gd:a});this.Df=a};b.prototype.getPhaseName=function(){return this.Df};b.prototype.getPhaseID=function(a){for(var c=0;c<b.ec.length;c++)if(b.ec[c]===a)return c;return null};b.prototype.getPhaseCallbackTime=function(a){for(var b=this.Ga,e=0;e<b.length;e++)if(b[e].gd===a)return b[e].Yg;return null};b.prototype.findPhaseAtNominalTime=function(d){a.assert(0<=d);for(var c=this.Ga,e=c.length-1;0<=e;e--)if(d>=c[e].Xg)return c[e].gd;a.error("M16",d,a.utils.Lf(c));return b.Ja};b.Ja="AFTER_FIRST_BYTE";
b.$b="AFTER_DOM_INTERACTIVE";b.hc="AT_ONLOAD";b.bc="AFTER_ONLOAD";b.ec=[b.Ja,b.$b,b.hc,b.bc];return b}();a.li=b;a.lifecycle=new b;a.lifecycle=a.lifecycle})(g||(g={}));(function(a){(function(a){var f=function(a){function b(){a.apply(this,arguments)}v(b,a);b.prototype.type=function(){return 0};return b}(a.EventTracker);a.PageView=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.now,d=function(){function c(){}c.prototype.setUp=function(){var b=document.readyState;if("loading"===
b)a.log("M17"),c.Ah(),c.Dd();else{var d={timeStamp:f()};c.V(d);"interactive"===b?(a.log("M18"),c.Dd()):(a.log("M19"),c.ba(d),c.ed(d))}};c.Dd=function(){a.utils.addEventListener(window,"load",c.ba);a.utils.addEventListener(window,"load",c.ed)};c.ed=function(d){c.currentBasePage=new a.events.PageView;a.lifecycle.ah(d&&d.timeStamp);a.utils.Ba(function(){var d=f();a.lifecycle.$g(d);a.command("mark","onload",d);b.PerformanceMonitor.perf&&(b.perfMonitor.zf(),b.perfMonitor.Af());a.command("reportOnload",
c.currentBasePage);a.utils.loadScriptAsync(a.conf.adrumExtUrl)});a.log("M20")};c.Ah=function(){if(a.utils.isFunction(document.addEventListener))document.addEventListener("DOMContentLoaded",c.V,!1);else if(a.utils.isObject(document.attachEvent)){document.attachEvent("onreadystatechange",c.V);var b=null;try{b=null===window.frameElement?document.documentElement:null}catch(d){}null!=b&&b.doScroll&&function l(){if(!c.isReady){try{b.doScroll("left")}catch(a){setTimeout(l,10);return}c.ba()}}()}else a.exception("M21");
a.log("M22")};c.ba=function(b){c.Yc||(a.lifecycle.Zg(b&&b.timeStamp),a.command("mark","onready",f()),c.Yc=!0)};c.V=function(a){document.addEventListener?(document.removeEventListener("DOMContentLoaded",c.V,!1),c.ba(a)):"complete"===document.readyState&&(document.detachEvent("onreadystatechange",c.V),c.ba(a))};c.isReady=!1;c.Yc=!1;return c}();b.DOMEventsMonitor=d;b.Jf=new b.DOMEventsMonitor})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(b){var f=function(){function b(){this.navTiming=
this.resTiming=null}b.prototype.setUp=function(){b.perf=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;a.utils.isObject(b.perf)&&a.utils.isObject(b.perf.timing)||(b.perf=void 0);this.setResourceTimingBufferSize()};b.prototype.setResourceTimingBufferSize=function(){var c=b.perf,e=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.bufSize;!a.utils.isNumber(e)||0>=e?a.log("M23"):c&&a.utils.isFunction(c.setResourceTimingBufferSize)?c.setResourceTimingBufferSize(e):
a.log("M24setResourceTimingBufferSize is not supported")};b.prototype.zf=function(){var c=b.perf;if(c=c&&c.timing)if(c.navigationStart&&c.navigationStart<=c.loadEventEnd){var e={},m;for(m in c){var h=c[m];"number"===typeof h&&(e[m]=h)}this.navTiming=e}else a.log("M26");else a.log("M25")};b.prototype.Af=function(){this.resTiming=this.Dc()};b.prototype.Dc=function(){var c=b.perf,e=[];c&&c.getEntriesByType&&(c=c.getEntriesByType("resource"))&&c.length&&0<c.length&&c.unshift&&(e=c);0==e.length&&a.log("M27");
return e};b.perf=null;return b}();b.PerformanceMonitor=f;b.perfMonitor=new b.PerformanceMonitor})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(b){b.parseURI=function(a){var b=String(a).replace(/^\s+|\s+$/g,"").match(/^([^:\/?#]+:)?(?:\/\/(?:([^:@\/?#]*)(?::([^:@\/?#]*))?@)?(([^:\/?#]*)(?::(\d*))?))?([^?#]*)(\?[^#]*)?(#[\s\S]*)?/);a=b&&null!=a.match(b[1]+"//");return b&&{href:b[0]||"",protocol:b[1]||"",pb:a?"//":"",wb:b[2]||"",jb:b[3]||"",host:b[4]||"",hostname:b[5]||"",port:b[6]||
"",pathname:b[7]||"",search:b[8]||"",hash:b[9]||""}};b.absolutizeURI=function(a,d){function c(a){var b=[];a.replace(/^(\.\.?(\/|$))+/,"").replace(/\/(\.(\/|$))+/g,"/").replace(/\/\.\.$/,"/../").replace(/\/?[^\/]*/g,function(a){"/.."===a?b.pop():b.push(a)});return b.join("").replace(/^\//,"/"===a.charAt(0)?"/":"")}var e,m,h,l,k,g,p,n;n=d?b.parseURI(d):{};p=a?b.parseURI(a):{};n.protocol?(e=n.protocol,m=n.pb,h=n.wb,l=n.jb,k=n.host,g=c(n.pathname),p=n.search):n.host?(e=p.protocol,m=p.pb,h=n.wb,l=n.jb,
k=n.host,g=c(n.pathname),p=n.search):(e=p.protocol,m=p.pb,h=p.wb,l=p.jb,k=p.host,n.pathname?("/"===n.pathname.charAt(0)?g=c(n.pathname):(g=p.pathname?p.pathname.slice(0,p.pathname.lastIndexOf("/")+1)+n.pathname:m?"/"+n.pathname:n.pathname,g=c(g)),p=n.search):(g=c(p.pathname),p=n.search||p.search));return e+m+(h?h+(l?":"+l:"")+"@":"")+k+g+p+(n.hash?n.hash:"")};b.getFullyQualifiedUrl=function(f){try{var d,c=document.location.href,e;a:{for(var m=document.getElementsByTagName("base"),h=0;h<m.length;h++){var l=
m[h].href;if(l){e=l;break a}}e=void 0}d=e?b.absolutizeURI(c,e):c;return b.absolutizeURI(d,f)}catch(k){return a.exception(k,"M28",f,d),f}}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){a=a.events||(a.events={});a=a.b||(a.b={});a.navigationStart="navigationStart";a.domainLookupStart="domainLookupStart";a.domainLookupEnd="domainLookupEnd";a.connectStart="connectStart";a.secureConnectionStart="secureConnectionStart";a.connectEnd="connectEnd";a.requestStart="requestStart";a.responseStart="responseStart";
a.responseEnd="responseEnd";a.domContentLoadedEventStart="domContentLoadedEventStart";a.loadEventEnd="loadEventEnd";a.Ad="sendTime";a.xc="firstByteTime";a.ud="respAvailTime";a.vd="respProcTime";a.yb="viewChangeStart";a.Rd="viewChangeEnd";a.zb="viewDOMLoaded";a.Wd="xhrRequestsCompleted";a.Wi="viewFragmentsLoaded";a.Xi="viewResourcesLoaded";a.Ab="virtualPageStart";a.Xh="virtualPageEnd"})(g||(g={}));(function(a){a=a.events||(a.events={});a.metricSpec={};a.metricSpec[0]={Qf:{start:a.b.navigationStart,
end:a.b.loadEventEnd,name:"PLT"},Xf:{start:a.b.navigationStart,end:a.b.responseStart,name:"FBT"},Si:{start:a.b.navigationStart,end:a.b.requestStart,name:"SCT"},Ti:{start:a.b.secureConnectionStart,end:a.b.connectEnd,name:"SHT"},yi:{start:a.b.domainLookupStart,end:a.b.domainLookupEnd,name:"DLT"},Vi:{start:a.b.connectStart,end:a.b.connectEnd,name:"TCP"},Qi:{start:a.b.requestStart,end:a.b.responseStart,name:"RAT"},Ai:{start:a.b.responseStart,end:a.b.loadEventEnd,name:"FET"},Ci:{start:a.b.responseStart,
end:a.b.domContentLoadedEventStart,name:"DRT"},Bi:{start:a.b.responseStart,end:a.b.responseEnd,name:"DDT"},wi:{start:a.b.responseEnd,end:a.b.domContentLoadedEventStart,name:"DPT"},Pi:{start:a.b.domContentLoadedEventStart,end:a.b.loadEventEnd,name:"PRT"},xi:{start:a.b.navigationStart,end:a.b.domContentLoadedEventStart,name:"DOM"}};a.metricSpec[2]={Xf:{start:a.b.Ad,end:a.b.xc,name:"FBT"},pi:{start:a.b.xc,end:a.b.ud,name:"DDT"},oi:{start:a.b.ud,end:a.b.vd,name:"DPT"},Qf:{start:a.b.Ad,end:a.b.vd,name:"PLT"}};
a.metricSpec[3]={Ii:{start:a.b.Ab,end:a.b.Xh,name:"PLT"},ui:{start:a.b.yb,end:a.b.Rd,name:"DDT"},Fi:{start:a.b.yb,end:a.b.zb,name:"DRT"},fi:{start:a.b.Rd,end:a.b.zb,name:"DPT"},gi:{start:a.b.yb,end:a.b.zb,name:"DOM"},Oi:{start:"viewChangeEnd",end:"xhrRequestsCompleted",name:null},Gi:{start:"viewChangeEnd",end:"viewPartialsLoaded",name:null},Ei:{start:"viewPartialsLoaded",end:"viewFragmentsLoaded",name:null},Hi:{start:"viewPartialsLoaded",end:"viewResourcesLoaded",name:null}};a.metricSpec[102]=a.metricSpec[3]})(g||
(g={}));(function(a){(function(b){var f=function(d){function c(e){this.constructor!=c&&this.constructor!=b.AdrumAjax?a.reportAPIMessage(0,a.U,"ADRUM.events.Ajax",[]):d.call(this,e)}v(c,d);c.prototype.type=function(){return 2};return c}(b.EventTracker);b.Ajax=f;b.$(b.w[2],f.prototype);b.gc(b.metricSpec[2],f.prototype)})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(a){function b(c){a.call(this,c)}v(b,a);b.prototype.type=function(){return 2};return b}(a.Ajax);a.AdrumAjax=
f;a.$(a.w[101],f.prototype)})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.isObject,d=a.utils.isDefined,c=a.utils.map,e=a.utils.reduce,m=a.utils.filter,h=a.utils.$h,l=a.utils.isString,k=a.utils.Gf,g=a.utils.yf,p=a.utils.isFunction,n=a.utils.mergeJSON,s=a.utils.La,t=a.utils.now,u=a.utils.Ba,y=function(b){function r(){b.call(this);this.conf=null;this.rb=!1;this.Ka=0;!0===window["adrum-xhr-disable"]?a.log("M29"):window.XMLHttpRequest?(this.conf={exclude:[{urls:[{pattern:a.conf.beaconUrlHttp+
a.conf.corsEndpointPath},{pattern:a.conf.beaconUrlHttps+a.conf.corsEndpointPath}]}],include:[],maxPerPageView:r.Fb},r.md(this.conf,a.conf.userConf&&a.conf.userConf.xhr),(this.g=window.XMLHttpRequest.prototype)?"open"in this.g&&"send"in this.g?(this.rb=a.aop.support(this.g.open)&&a.aop.support(this.g.send))||a.log("M33"):a.log("M32"):a.log("M31")):a.log("M30")}v(r,b);r.md=function(b,c){var d=r.Fb;if(c){var l=c.maxPerPageView;a.utils.isNumber(l)&&0<l?d=l:a.reportAPIMessage(4,"value is not valid; don't limit xhr",
"xhr.maxPerPageView",[l])}b.maxPerPageView=d;b.exclude=r.xb(r.Qd,"exclude",b,c);b.include=r.xb(r.Qd,"include",b,c);b.parameter=r.xb(r.Vh,"parameter",c)};r.xb=function(a,b){for(var d=[],l=2;l<arguments.length;l++)d[l-2]=arguments[l];return k(c(m(g(c(k(d),function(a){return h(a[b])})),r.Gg(b)),a))};r.Qd=function(a){var b=r.kd(a);a=r.ld(a);return b||a};r.Gg=function(b){return function(c){return f(c)||a.reportAPIMessage(2,"Filter object must be an object","xhr."+b,[c])}};r.ld=function(a){var b=a.urls;
if(b&&0<b.length&&(a.urls=r.Cf(b),0<a.urls.length))return a};r.kd=function(b){var c=b.method;if(d(c)){if(l(c))return b;a.error("M34")}};r.Vh=function(a){var b=r.ld(a);r.kd(a);return r.mh(a)&&b};r.mh=function(b){if(p(b.getFromBody))return b;a.error("M35")};r.Cf=function(b){for(var c=[],d=0;d<b.length;d++){var l=b[d].pattern;if("string"===typeof l)try{c.push(new RegExp(l))}catch(h){a.exception(h,"Parse regex pattern failed.")}else a.error("xhr filter pattern should be a string")}return c};r.Ed=function(a,
b,c){var d=c&&c.include;c=c&&c.exclude;return d&&0<d.length&&!r.Sc(b,a,d)||c&&0<c.length&&r.Sc(b,a,c)};r.uc=function(b){var c=b.message||b.description,d=b.fileName||b.filename,l=b.lineNumber;a.utils.isString(b.description)&&0<=b.description.indexOf("Access is denied.")&&(c+=": maybe you have CORS XHR error in IE");a.monitor.ra.pd(c,d,l,b)};r.prototype.setUp=function(){if(this.rb){a.log("M36");a.xhrConstructor=window.XMLHttpRequest;a.xhrOpen=this.xhrOpen=this.g.open;a.xhrSend=this.xhrSend=this.g.send;
var b=this;this.g.open=a.aop.around(this.g.open,function(){r.Jg(this)&&(4===this.readyState?(a.log("M37"),r.Rf(this._adrumAjaxT),delete this.Zb,r.a(this,this._adrumAjaxT)):a.log("M38"+this._adrumAjaxT.url()+"' is reported."));var c=1<=arguments.length?String(arguments[0]):"",d=2<=arguments.length?String(arguments[1]):"",d=a.utils.getFullyQualifiedUrl(d);b.Ka>=b.conf.maxPerPageView||r.Ed(d,c,b.conf)||(this._adrumAjaxT=new a.events.AdrumAjax(a.utils.mergeJSON({method:c,url:d},b.status)))},null,"XHR.open",
r.uc);this.g.send=a.aop.around(this.g.send,function(d){var l=this,h=this._adrumAjaxT;if(h&&!(++b.Ka>b.conf.maxPerPageView)){var e=a.utils.now(),m=h.getSendTime();a.assert(null===m,"M39");h.timestamp(e);h.markSendTime(m||e);h.parentPhase(a.lifecycle.getPhaseName());r.Kg(h.url())?l.setRequestHeader("ADRUM","isAjax:true"):a.log("M40",document.location.href,h.url());d=r.ig(h.url(),b.conf.parameter,d);h.parameter(d);var k=0,g=function(){if(4==l.readyState)a.log("M41"),b.Ha(l);else{var d=null;try{d=l.onreadystatechange}catch(h){a.log("M42",
h);b.Ha(l);return}k++;d?a.aop.support(d)?(l.onreadystatechange=r.pc(d,"XHR.onReadyStateChange"),a.log("M43",k)):c||(a.log("M44"),b.Ha(l)):k<r.ff?a.utils.Ba(g):c?a.log("M45"):(a.log("M46"),b.Ha(l))}};c&&b.bi.call(l,"readystatechange",r.Hf);g()}},null,"XHR.send",r.uc);var c="addEventListener"in this.g&&"removeEventListener"in this.g&&a.aop.support(this.g.addEventListener)&&a.aop.support(this.g.removeEventListener);c?(this.bi=this.g.addEventListener,this.g.addEventListener=a.aop.around(this.g.addEventListener,
function(b,c){if(/^(load|error|readystatechange)$/.test(b)&&c){var d=r.Rh(c);if(d){var l=s(arguments);l[1]=d;a.log("M47");return l}a.log("M48",b,c)}},null,"XHR.addEventListener"),this.di=this.g.removeEventListener,this.g.removeEventListener=a.aop.around(this.g.removeEventListener,function(c,d){if(this._adrumAjaxT){var l=s(arguments);d.__adrumInterceptor?(l[1]=d.__adrumInterceptor,a.log("M49"),b.di.apply(this,l)):a.log("M50")}},null,"XHR.removeEventListener")):a.log("M51");a.log("M52")}};r.prototype.sd=
function(){this.Ka=0};r.Zc=function(a,b){for(var c=!1,d=0;d<b.length;d++){var l=b[d];if(l&&l.test(a)){c=!0;break}}return c};r.Sc=function(a,b,c){var d=!1;if(b&&c)for(var l=0;l<c.length;l++){var h=c[l];if(!(h.method&&a!==h.method||h.urls&&!r.Zc(b,h.urls))){d=!0;break}}return d};r.jh=function(a,b,c){return(b||a)===(c||a)};r.Kg=function(a){var b=document.createElement("a");b.href=a;a=document.location;var c=a.protocol;return b.protocol===c&&b.hostname===a.hostname&&r.jh(r.Ff[c],b.port,a.port)};r.ig=
function(a,b,d){if(b&&(b=m(c(m(b,function(b){return r.Zc(a,b.urls)}),function(a){return a.getFromBody(d)}),f),0<b.length))return e(b,n,{})};r.Ya=function(a){var b=a._adrumAjaxT;if(b){var c=(new Date).getTime();2==a.readyState?b.markFirstByteTime(b.getFirstByteTime()||c):4==a.readyState&&(b.markRespAvailTime(b.getRespAvailTime()||c),b.markFirstByteTime(b.getFirstByteTime()||c))}};r.Ic=function(a){var b=a._adrumAjaxT;if(b&&4==a.readyState){var c=t(),d=b.getRespProcTime();b.markRespAvailTime(b.getRespAvailTime()||
c);c>d&&b.markRespProcTime(c);r.zd(a,b)}};r.pc=function(a,b){return r.ci(a,function(){r.Ya(this)},function(){r.Ic(this)},b)};r.Hf=function(){r.Ya(this);r.Ic(this)};r.Jg=function(b){return a.utils.isDefined(b._adrumAjaxT)&&a.utils.isString(b._adrumAjaxT._url)};r.Rf=function(a){var b=(new Date).getTime();a.markRespAvailTime(a.getRespAvailTime()||b);a.markFirstByteTime(a.getFirstByteTime()||b);a.markRespProcTime(a.getRespProcTime()||b)};r.zd=function(a,b){var c={};a.Zb=c;u(function(){a.Zb===c&&(delete a._adrumAjaxT,
r.a(a,b))})};r.a=function(b,c){var d=b.status,h;c.xhrStatus(d);c.allResponseHeaders(b.getAllResponseHeaders());if(400<=d){try{l(b.responseText)&&(h=b.responseText)}catch(e){l(b.responseType)&&(h=b.responseType)}c.error({status:d,msg:h})}a.command("reportXhr",c)};r.prototype.Ha=function(b){if(b._adrumAjaxT){var c=(new Date).getTime()+3E4,d=function(){r.Ya(b);var l=b._adrumAjaxT;if(l){var h=(new Date).getTime();4==b.readyState?(a.assert(null===l.getRespProcTime(),"M53"),l.markRespProcTime(l.getRespProcTime()||
h),a.log("M54"),r.zd(b,l)):h<c?setTimeout(d,r.Gb):(delete b._adrumAjaxT,a.log("M55"))}};d()}};r.ci=function(b,c,d,l){var h=b;b&&"object"===typeof b&&"toString"in b&&"[xpconnect wrapped nsIDOMEventListener]"===b.toString()&&"handleEvent"in b&&(h=function(){b.handleEvent.apply(this,s(arguments))});return a.aop.around(h,c,d,l)};r.Rh=function(b){if(b.__adrumInterceptor)return b.__adrumInterceptor;if(a.aop.support(b)){var c=r.pc(b,"XHR.invokeEventListener");return b.__adrumInterceptor=c}};r.ff=5;r.Gb=
50;r.Fb=50;r.Ff={"http:":"80","https:":"443"};return r}(b.Hb);b.ma=y;b.ha=new b.ma})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){(function(b){function g(a,b){var c=[],d=/^\s*(ADRUM_BT\w*)=(.*)\s*$/i.exec(a);if(d){var f=d[1],d=d[2].replace(/^"|"$/g,""),d=decodeURIComponent(d).split("|"),p=d[0].split(":");if("R"===p[0]&&Number(p[1])===b)for(e(f),f=1;f<d.length;f++)c.push(d[f])}return c}function d(a,b){var c=/^\s*(ADRUM_(\d+)_(\d+)_(\d+))=(.*)\s*$/i.exec(a);if(c){var d=c[1],g=c[4],f=c[5];if(Number(c[3])===
b)return e(d),{index:Number(g),value:f}}return null}function c(b){var c=/^\s*ADRUM=s=([\d]+)&r=(.*)\s*/.exec(b);if(c){a.log("M58",b);if(3===c.length)return e("ADRUM"),{startTime:Number(c[1]),startPage:c[2]};a.error("M59",b);return null}}function e(b){a.log("M57",b);var c=new Date;c.setTime(c.getTime()-1E3);document.cookie=b+"=;Expires="+c.toUTCString()}b.startTimeCookie=null;b.cookieMetadataChunks=null;b.sc=function(e,h){a.log("M56");for(var l=h?h.length:0,k=[],q=e.split(";"),p=0;p<q.length;p++){var n=
q[p],s=d(n,l);s?k.push(s):(n=c(n),null!=n&&(b.startTimeCookie=n))}Array.prototype.sort.call(k,function(a,b){return a.index-b.index});n=[];for(p=0;p<k.length;p++)n.push(k[p].value);for(p=0;p<q.length;p++)(k=g(q[p],l))&&0<k.length&&(n=n.concat(k));b.cookieMetadataChunks=n};a.correlation.eck=b.sc})(a.correlation||(a.correlation={}))})(g||(g={}));(function(a){a.report=function(b){a.utils.isObject(b)&&a.utils.isFunction(b.type)?-1==[0,2,3,4].indexOf(b.type())?a.reportAPIMessage(0,b.type()+"is not a valid external event type",
"ADRUM.report",Array.prototype.slice.call(arguments)):a.utils.Ba(function(){a.command("reportEvent",b)}):a.reportAPIMessage(1,"","ADRUM.report",Array.prototype.slice.call(arguments))}})(g||(g={}));(function(a){"APP_KEY_NOT_SET"===a.conf.appKey&&A.log("AppDynamics EUM cloud application key missing. Please specify window['adrum-app-key']");a.correlation.sc(document.cookie,document.referrer);a.command("mark","firstbyte",window["adrum-start-time"]);a.monitor.Cd(a.monitor.ra,a.monitor.Jf,a.monitor.perfMonitor,
a.monitor.ha)})(g||(g={}));(function(a){a=a.ng||(a.ng={});a=a.c||(a.c={});a.Wc="locationChangeStart";a.Sg="locationChangeSuccess";a.wd="routeChangeStart";a.yd="routeChangeSuccess";a.Gd="stateChangeStart";a.Hd="stateChangeSuccess";a.Sd="viewContentLoaded";a.sg="includeContentRequested";a.rg="includeContentLoaded";a.qc="digest";a.Li="outstandingRequestsComplete";a.jc="beforeNgXhrRequested";a.ac="afterNgXhrRequested";a.Ki="ngXhrLoaded";a.mc="$$completeOutstandingRequest"})(g||(g={}));(function(a){(function(b){function g(a,
c,d,l,k,f){if(c)try{return c.apply(a,[d,l,k].concat(f))}catch(p){return a.error(d,l,k,f,b.Error.se,"an exception occurred in a caller-provided callback function",p)}}function d(a,c){return function(){var d=this.current,l=c[d]||c[b.la]||d,k=Array.prototype.slice.call(arguments);if(this.wf(a))return this.error(a,d,l,k,b.Error.te,"event "+a+" inappropriate in current state "+this.current);if(!1===g(this,this["onbefore"+a],a,d,l,k))return b.ka.Cb;l===b.la&&(l=d);if(d===l)return g(this,this["onafter"+
a]||this["on"+a],a,d,l,k),b.ka.Se;var q=this;this.transition=function(){q.transition=null;q.current=l;g(q,q["onenter"+l]||q["on"+l],a,d,l,k);g(q,q["onafter"+a]||q["on"+a],a,d,l,k);return b.ka.$e};if(!1===g(this,this["onleave"+d],a,d,l,k))return this.transition=null,b.ka.Cb;if(this.transition)return this.transition()}}var c=a.utils.hasOwnPropertyDefined;b.VERSION="2.3.5";b.ka={$e:1,Se:2,Cb:3,ji:4};b.Error={te:100,ki:200,se:300};b.la="*";b.create=function(a,m){function h(a){var c=a.from instanceof Array?
a.from:a.from?[a.from]:[b.la];n[a.name]=n[a.name]||{};for(var d=0;d<c.length;d++)s[c[d]]=s[c[d]]||[],s[c[d]].push(a.name),n[a.name][c[d]]=a.to||c[d]}var l="string"==typeof a.initial?{state:a.initial}:a.initial,k=m||a.target||{},g=a.events||[],f=a.callbacks||{},n={},s={};l&&(l.event=l.event||"startup",h({name:l.event,from:"none",to:l.state}));for(var v=0;v<g.length;v++)h(g[v]);for(var u in n)c(n,u)&&(k[u]=d(u,n[u]));for(u in f)c(f,u)&&(k[u]=f[u]);k.current="none";k.Di=function(a){return a instanceof
Array?0<=a.indexOf(this.current):this.current===a};k.vf=function(a){return!this.transition&&(c(n[a],this.current)||c(n[a],b.la))};k.wf=function(a){return!this.vf(a)};k.Ga=function(){return s[this.current]};k.error=a.error||function(a,b,c,d,l,h,e){throw e||h;};if(l&&!l.defer)k[l.event]();return k}})(a.Ub||(a.Ub={}))})(g||(g={}));(function(a){(function(b){var g=function(d){function c(b){this.constructor!=a.ng.NgVPageView&&this.constructor!=c?a.reportAPIMessage(0,a.U,"ADRUM.events.VPageView",[]):(d.call(this,
b),this.perf=new a.PerformanceTracker,this.start(),a.monitor.ha.sd(),a.monitor.ra.qh())}v(c,d);c.prototype.type=function(){return 3};c.prototype.eg=function(){return b.EventTracker.fc(this.guid(),this.url(),this.type())};c.prototype.Fd=function(b){var c=this.eg();b.set("parent",c);a.log("M60",c.guid(),c.url())};c.prototype.startCorrelatingXhrs=function(){a.log("M61");this.Fd(a.monitor.ha)};c.prototype.stopCorrelatingXhrs=function(){a.monitor.ha.set("parent",null);a.log("M62")};c.prototype.Dh=function(){a.log("M63");
this.Fd(a.monitor.ra)};c.prototype.start=function(){this.markVirtualPageStart();this.startCorrelatingXhrs()};c.prototype.end=function(){this.markVirtualPageEnd();this.stopCorrelatingXhrs()};return c}(b.EventTracker);b.VPageView=g;b.$(b.w[3],g.prototype);b.gc(b.metricSpec[3],g.prototype)})(a.events||(a.events={}))})(g||(g={}));(function(a){var b=a.ng||(a.ng={}),b=b.conf||(b.conf={});b.disabled=a.conf.userConf&&a.conf.userConf.spa&&a.conf.userConf.spa.angular&&a.conf.userConf.spa.angular.disable;b.distinguishVPwithItsTemplateUrl=
a.conf.userConf&&a.conf.userConf.spa&&a.conf.userConf.spa.angular&&!0===a.conf.userConf.spa.angular.distinguishVPwithItsTemplateUrl?!0:!1;b.xhr={};b.metrics={includeResTimingInEndUserResponseTiming:!0};a.conf.userConf&&a.conf.userConf.spa&&a.conf.userConf.spa.angular&&a.conf.userConf.spa.angular.vp&&(a.conf.userConf.spa.angular.vp.xhr&&a.monitor.ma.md(b.xhr,a.conf.userConf.spa.angular.vp.xhr),a.conf.userConf.spa.angular.vp.metrics&&a.utils.mergeJSON(b.metrics,a.conf.userConf.spa.angular.vp.metrics))})(g||
(g={}));(function(a){(function(b){var g=a.utils.map,d=a.utils.reduce,c=a.utils.filter,e=function(e){function h(b){e.call(this,b);this.Qc=!0;this.ca={};this.T=0;this.constructor!=h?a.reportAPIMessage(0,a.U,"ADRUM.events.Ajax",[]):this.stopCorrelatingXhrs()}v(h,e);h.prototype.type=function(){return 3};h.prototype.Ab=function(){this.markViewChangeStart();this.markVirtualPageStart(this.getViewChangeStart());this.timestamp(this.getViewChangeStart())};h.prototype.tg=function(){this.digestCount(this.digestCount()+
1)};h.prototype.ug=function(){this.T++;a.log("M64",this.T)};h.prototype.Ef=function(){this.T--;a.log("M65",this.T)};h.prototype.og=function(){var b=this.perf.getEntryByName(a.events.b.Wd);a.log("M66",this.T,b);return 0<this.T};h.prototype.sf=function(){var a={Fa:0},b=document.querySelectorAll("ng-view, [ng-view], .ng-view, [ui-view]"),b=g(b,angular.element),c;for(c in h.td){var d=h.td[c];g(b,function(b){b=b.find(c);g(b,function(b){if(b=b[d])b=decodeURIComponent(b),a[b]||(a[b]=c,a.Fa++)})})}this.ca=
a};h.prototype.rf=function(a){return!!this.ca[decodeURIComponent(a.name)]};h.prototype.tf=function(){var b=[],c=this;0<this.ca.Fa&&(b=a.monitor.perfMonitor.Dc().filter(function(a){return c.rf(a)}));this.resTiming(b)};h.Uf=function(d){return c(d,function(c){return(2===c.eventType||101===c.eventType)&&!a.monitor.ma.Ed(c.eventUrl,c.method,b.conf.xhr)})};h.fg=function(a){return d(a,function(a,b){return Math.max(a,b.timestamp+b.metrics.PLT)},-1)};h.prototype.mf=function(){if(b.conf.xhr){var c=h.Uf(a.channel.getEventsWithParentGUID(this.guid())),
c=h.fg(c);if(0<c){var d=this.perf.getEntryByName(a.events.b.Wd);this.markXhrRequestsCompleted(Math.min(d&&d.startTime||Number.MAX_VALUE,c))}}};h.prototype.adjustTimings=function(){this.mf();var c=this.getViewDOMLoaded(),d=this.getXhrRequestsCompleted(),c=Math.max(c,d);b.conf.metrics.includeResTimingInEndUserResponseTiming&&(this.lf(),d=this.getViewResourcesLoaded(),d=Math.max(c,d),a.log("M67",c,d),c=d);this.markVirtualPageEnd(c)};h.prototype.lf=function(){if(0<this.ca.Fa){this.tf();var b=this.resTiming();
b&&b.length>=this.ca.Fa&&(b=d(b,function(a,b){return Math.max(a,b.responseEnd)},0),this.markViewResourcesLoaded(a.PerformanceTracker.Na(b)))}};h.prototype.identifier=function(b){var c=this.Ud;a.utils.isDefined(b)&&(this.Ud=h.Sf(b),this.url(this.Ud.url));return c};h.Sf=function(b){var c={};b&&b.j?(c.j={hb:""},a.utils.mergeJSON(c.j,{hb:b.j.originalPath,da:b.j.template,ea:b.j.templateUrl})):b&&b.state&&(c.state={url:""},a.utils.mergeJSON(c.state,{url:b.state.url,name:b.state.name,da:b.state.template,
ea:b.state.templateUrl}));return c};h.td={img:"src",script:"src",link:"href"};return h}(a.events.VPageView);b.NgVPageView=e;a.events.$(a.events.w[102],e.prototype)})(a.ng||(a.ng={}))})(g||(g={}));(function(a){(function(b){var g=function(){function d(){this.h=new b.NgVPageView}d.prototype.uh=function(){var c=this;b.conf.metrics.includeResTimingInEndUserResponseTiming?(a.log("M68"),setTimeout(function(){c.kb()},d.bf)):setTimeout(function(){c.kb()},d.cf)};d.prototype.kb=function(){a.log("M69");var b=
this.h;b.parent(a.monitor.DOMEventsMonitor.currentBasePage);a.command("call",function(){b.adjustTimings();a.reporter.reportEvent(b)})};d.prototype.zh=function(a){this.h=a};d.bf=5E3;d.cf=2*a.monitor.ma.Gb;return d}();b.VirtualPageStateMachine=g;a.Ub.create({events:[{name:"start",from:"none",to:"ChangeView"},{name:"viewLoaded",from:"ChangeView",to:"XhrPending"},{name:"xhrCompleted",from:"XhrPending",to:"End"},{name:"abort",from:"*",to:"none"},{name:"init",from:"*",to:"none"},{name:"locChange",from:"*",
to:"*"},{name:"beforeXhrReq",from:"*",to:"*"},{name:"afterXhrReq",from:"*",to:"*"}],error:function(b){a.log("M70"+b)},callbacks:{onChangeView:function(){this.h.Ab();this.h.Dh()},onviewLoaded:function(){this.h.markViewDOMLoaded()},onXhrPending:function(){this.h.Qc&&this.xhrCompleted()},onleaveXhrPending:function(a,b,e){if("abort"===a)return this.kb(),!0;if("xhrCompleted"===a&&"End"===e){if(this.h.og())return!1;this.h.markXhrRequestsCompleted();return!0}},onEnd:function(){this.h.sf();this.uh()},oninit:function(b,
c,e,g){this.zh(g);a.monitor.ha.sd()},onlocChange:function(a,b,e,g){this.h.identifier.url=g;this.h.Ea({url:g})},onbeforeXhrReq:function(b,c,e,g){var h=this.h;h.Qc=!1;a.log("M71",g&&g[1]||"",h.guid());h.ug();h.startCorrelatingXhrs();g[3]&&(g[3]=a.aop.before(g[3],function(b,c,d){a.log("M72");h.Ef();d&&(b=a.utils.ih(d)["content-type"])&&0<=b.indexOf("text/html")&&h.markViewFragmentsLoaded()}));return g},onafterXhrReq:function(){this.h.stopCorrelatingXhrs()}}},g.prototype)})(a.ng||(a.ng={}))})(g||(g={}));
(function(a){(function(b){var g=function(){function d(){this.k=new b.VirtualPageStateMachine;this.distinguishVPwithItsTemplateUrl=a.ng.conf.distinguishVPwithItsTemplateUrl}d.prototype.l=function(c,e){a.log("M73",c);switch(c){case b.c.wd:case b.c.Gd:this.k.start();var g=e.next.url||document.URL,h=new b.NgVPageView({url:g,identifier:e.next});this.distinguishVPwithItsTemplateUrl&&d.Cg(this.k.h,h)?this.k.h.Ea({url:g,identifier:e.next}):this.Jh(h);break;case b.c.yd:case b.c.Hd:this.k.h.markViewChangeEnd();
break;case b.c.Sd:this.k.viewLoaded();break;case b.c.jc:this.k.beforeXhrReq(e);break;case b.c.ac:this.k.afterXhrReq();break;case b.c.mc:this.k.xhrCompleted();break;case b.c.Wc:this.k.h.Ea({url:e.next.url});this.k.locChange(e.next.url);break;case b.c.qc:this.k.h.tg()}};d.prototype.Jh=function(a){this.k.abort();this.k.init(a);this.k.start()};d.Cg=function(b,d){var g=b.identifier(),h=d.identifier(),l=!1;return l=!a.utils.isDefined(g)&&!a.utils.isDefined(h)||g===h?!0:a.utils.isDefined(g)&&a.utils.isDefined(h)?
g.state||h.state?a.utils.isDefined(g.state)&&a.utils.isDefined(h.state)?g.state.name===h.state.name&&g.state.da===h.state.da&&g.state.ea===h.state.ea&&g.state.url===h.state.url:!1:g.j&&h.j?g.j.hb===h.j.hb&&g.j.da===h.j.da&&g.j.ea===h.j.ea:g.url===h.url:!1};return d}();b.df=g})(a.ng||(a.ng={}))})(g||(g={}));(function(a){(function(b){var g=a.utils.addEventListener,d=function(){function c(){this.n=new b.df;this.Oc=!1}c.prototype.setUp=function(){function b(d){return function(){a.log(d);c.init()}}var c=
this;b("M74")();g(document,"DOMContentLoaded",b("M75"));g(window,"load",b("M76"))};c.prototype.init=function(){if("undefined"!=typeof angular&&!this.Oc){this.Oc=!0;a.log("M77");var b=this,c=angular.module("ng");c.config(["$provide",function(a){b.zg(a);b.yg(a)}]);c.run(["$browser",function(a){b.xg(a)}]);a.log("M78")}};c.prototype.yg=function(c){var d=a.aop,h=this;c.decorator("$httpBackend",["$delegate",function(a){return a=d.around(a,function(){var a=Array.prototype.slice.call(arguments);h.n.l(b.c.jc,
a);return a},function(){h.n.l(b.c.ac)},"ng.httpBackend")}])};c.prototype.zg=function(c){var d=a.aop,h=this;c.decorator("$rootScope",["$delegate",function(a){a.$digest=d.after(a.$digest,function(){h.n.l(b.c.qc)},"ngevents.digest");a.$on("$locationChangeStart",function(a,c){var d={url:c},g=a&&a.aa&&a.aa.$state&&a.aa.$state.current;g&&(d.state=g);h.n.l(b.c.Wc,{next:d})});a.$on("$locationChangeSuccess",function(){h.n.l(b.c.Sg)});a.$on("$routeChangeStart",function(a,c){var d={url:location.href},g=c&&c.$$route;
g&&(d.j=g);h.n.l(b.c.wd,{next:d})});a.$on("$routeChangeSuccess",function(){h.n.l(b.c.yd)});a.$on("$stateChangeStart",function(a,c){h.n.l(b.c.Gd,{next:{state:c}})});a.$on("$stateChangeSuccess",function(){h.n.l(b.c.Hd)});a.$on("$viewContentLoaded",function(a){var c={url:location.href};if(a=a&&a.aa&&a.aa.$state&&a.aa.$state.current)c.state=a;h.n.l(b.c.Sd,{next:c})});a.$on("$includeContentRequested",function(){h.n.l(b.c.sg)});a.$on("$includeContentLoaded",function(){h.n.l(b.c.rg)});return a}])};c.prototype.xg=
function(c){var d=this;c.$$completeOutstandingRequest=a.aop.before(c.$$completeOutstandingRequest,function(){d.n.l(b.c.mc)})};return c}();b.ei=d;b.ngMonitor=new d})(a.ng||(a.ng={}))})(g||(g={}));(function(a){var b=a.ng||(a.ng={});b.conf.disabled||a.monitor.Cd(b.ngMonitor)})(g||(g={}))}};})();
